openapi: 3.2.0
info:
  title: Pendle V2 API Docs Chains API
  description: '## Terms used in the documentation/API


    Below are some terms used in the documentation/API:


    - Pendle Assets/Tokens: PT, YT, LP, SY

    - Non-Pendle Assets: other tokens that are not Pendle assets, such as USDC, USDT, DAI, etc.'
  version: '1.0'
  contact: {}
servers:
- url: http://127.0.0.1:9000
tags:
- name: Chains
paths:
  /v1/chains:
    get:
      operationId: ChainsController_getSupportedChainIds
      parameters: []
      responses:
        '200':
          description: List of blockchain networks supported by Pendle, returned as decimal numbers.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChainIdsResponse'
      summary: Get supported chain IDs
      tags:
      - Chains
      x-computing-unit: '1'
      x-retail-api-rank: 6969
components:
  schemas:
    ChainIdsResponse:
      type: object
      properties:
        chainIds:
          type: array
          items:
            type: number
      required:
      - chainIds
